name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Specify the OS for the job to run on

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Change directory and install dependencies
      run: |
        cd project/COMP.SE.200-2024-2025-1
        npm install

    - name: Verify dependencies installed
      run: |
        cd project/COMP.SE.200-2024-2025-1
        npm list

    - name: Run tests with coverage
      run: |
        cd project/COMP.SE.200-2024-2025-1
        npm test -- --coverage || true

    - name: List coverage directory for debugging
      run: |
        dir project/COMP.SE.200-2024-2025-1/coverage

    - name: Display lcov.info content
      run: |
        type project/COMP.SE.200-2024-2025-1/coverage/lcov.info
        
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2.3.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "project/COMP.SE.200-2024-2025-1/coverage/lcov.info"
      continue-on-error: true  # This will ensure Coveralls upload happens even if tests fail
  
        
