name: Node.js CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: windows-latest  # Specify the OS for the job to run on

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository's code

    - name: Print current directory (for debugging)
      run: dir  # Prints the current directory contents on Windows

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # Use the Node.js version v22.12.0

    - name: Change directory to where package.json is located and install dependencies
      run: |
        cd project/COMP.SE.200-2024-2025-1  # Navigate to the folder with package.json
        dir  # List files to confirm we're in the correct directory
        npm install  # Install dependencies defined in package.json

    - name: Verify dependencies installed
      run: |
        cd project/COMP.SE.200-2024-2025-1  # Navigate again to make sure we're in the correct directory
        dir  # Confirm node_modules exists
        npm list  # Check that all packages are installed

    - name: Run tests with coverage
      run: |
        cd project/COMP.SE.200-2024-2025-1  # Navigate to the folder with package.json
        npm test -- --coverage  # Run tests and collect coverage

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2.3.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
